Stop Overtone instruments on shutdown
This code doesn't work. First of all, in order to capture the ^C signal, `lein trampoline run` must be called to make sure the signal calls into the JVM at the right level. Secondly, this piece of code triggers an exception:

java.lang.IllegalArgumentException: No implementation of method: :group-deep-clear of protocol: #'overtone.sc.node/ISynthGroup found for class: nil

Presumably because by the time the shutdownHook thread runs, the Overtone process is already gone.